# -*- coding: utf-8 -*-
"""Shwetank Choubey movies.EXAM

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pZPgWKWKHBE6-XfwzXLKWQv9-GArTWF7
"""

#q7popularity  above 100
mydf['popularity']>=100
mydf['title']
mydf['tagline']

#Q4 RUNTIME GREATER THAN 90
len(mydf[mydf["runtime"]>=90])

#Q9
mydf['revenue'].sum()

from pandas import *
mydf=read_csv('/content/moviesData.csv')
mydf

mydf.columns

"""**
# Q3.How many movies were released ?
**
"""

mydf.groupby('release_date')['production_companies'].count().sum()

"""# Q4.What is the average revenue for movies released in each country?"""

mydf.groupby('production_countries')["revenue"].mean()

"""# Q5.What is the average budget for movies of each genre?"""

mydf.groupby("genres")['budget'].mean()

"""# Q6.Which production company has the highest average vote count for their movies?"""

mydf.groupby("production_companies")["vote_count"].mean().sort_values().tail(1)

"""# **Q8.How many movies were released by each production company?**"""

mydf.groupby("production_companies")["production_companies"].count()

"""# Q9.What is the average budget for movies of each original language?"""

#Q.What is the average budget for movies of each original language?

mydf.groupby("original_language")["budget"].mean()

"""# *Q10.Which genre has the highest total revenue?*"""

#Q.Which genre has the highest total revenue?
(mydf.groupby("genres")["revenue"].sum()).sort_values().tail(1)
#max(mydf.groupby("genres")["revenue"].sum())

mydf.info()
